is_debug: true
listen:
  type: port
  port: 1234
storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
google_api_key: AIzaSyB4TPzuXJNY31cvAc4l5xEO9A3wACthmNE
google_credentials_file: default_credentials.json