GET http://localhost:1234/courses
content-type: application/json

{}

####
PUT http://localhost:1234/
content-type: application/json

{}
####
PATCH http://localhost:1234/
content-type: application/json

{}
####
DELETE http://localhost:1234/
content-type: application/json

{}